name: Node Continous Integration

on:
  pull_request:
    branches: [main] # Triggers when a pull request is made to the main branch

jobs:
  tests_pull_request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 # Checks out GitHub repo using version 2 of "actions"
      - uses: actions/setup-node@v1 # Sets up Node
        with:
          node-version: 16 # GitHub Actions currently uses Node16
      - run: npm ci # Ensures updated dependencies
      - run: npm run test # Runs the script '"test": "jest"' in package.json, which executes the tests
  prettier_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 # Checks out GitHub repo using version 2 of "actions"
      - uses: actions/setup-node@v1 # Sets up Node
        with:
          node-version: 16 # GitHub Actions currently uses Node16
      - run: npx prettier --check . # Checks if the files are stylistically correct
  coveralls:
    runs-on: windows-latest
    strategy:
      matrix:
        test_number:
          - 1
          - 2
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@3
      with:
        node-version: 16.x

    - name: npm install
      run: npm install

    - name: Test ${{ matrix.test_number }}
      run: make test-coverage-${{ matrix.test_number }}
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@v1
      with:
        flag-name: run-${{ join(matrix.*, '-') }}
        parallel: true

  finish:
    needs: tests_pull_request
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v1
      with:
        parallel-finished: true
        carryforward: "run-1,run-2"

