name: Node Continous Integration

on:
  pull_request:
    branches: [main] # Triggers when a pull request is made to the main branch

jobs:
  tests_pull_request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 # Checks out GitHub repo using version 2 of "actions"
      - uses: actions/setup-node@v1 # Sets up Node
        with:
          node-version: 16 # GitHub Actions currently uses Node16
      - name: npm ci, run tests
        run: |
          npm ci 
          npm run test && get-content coverage/lcov.info | node_modules\coveralls\bin\coveralls.js
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0

  prettier_check:
    runs-on: windows-latest
    steps:
      - name: Check style
        run: npx prettier --check *.js # Checks if the files are stylistically correct
